### ISSUE TITLE
distorded background

### ISSUE THREAD

**Issue by JaKooLit** [JaKooLit/Hyprland-Dots#184]
some work around

https://github.com/LGFae/swww/issues/233

**Comment by coacharnold1** [comment]
thanks for the help  glad there is a workaround ...    I can't fugure out where the swww command is on the dot files ...  to put this:


The workaround is simply starting the daemon with the command swww-daemon --format xrgb. This issue is only caused when the wayland's buffer's format is in bgr in some integrated displays.

**Comment by heydoyouknowme0** [comment]
replace `swww init` with `swww-daemon --format xrgb`.
in Startup_Apps.conf and WallpaperSelect.sh


also
![image](https://github.com/JaKooLit/Hyprland-Dots/assets/68548165/42eef0d1-0a5a-478f-ba4c-7bd26b5c840b)

**Comment by andreatsilva** [comment]
If anyone is still  having this problem, i spent my entire night trying to solve it because "swww-daemon -f xrgb" was not working.

So here are the steps i tookto permanently solve this issue.

1) swww kill
2) mousepad .config/hypr/UserConfigs.conf

On the "#Wallpaper stuff" change the "swww init" to "swww-daemon -f xrgb"

**Comment by JaKooLit** [comment]
closing this as the swww developer have fixed the issue

https://github.com/LGFae/swww/issues/233
